### ISSUE TITLE
error，what happend? python train.py --config=config/toponet_vitb_512_cityscale.yaml

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [htcr/sam_road#1]
![image](https://github.com/htcr/sam_road/assets/42159103/7500ae4e-810b-4e32-9bb9-293281951123)

**Comment by EchoQiHeng** [comment]
May I ask how you solved it? Is it a problem with the torch version?

**Comment by EchoQiHeng** [comment]
> May I ask how you solved it? Is it a problem with the torch version?

Solved. pairs[:, :, 0].long()
