### ISSUE TITLE
Number of epochs

### ISSUE THREAD

**Issue by kurdt23** [htcr/sam_road#10]
Hello, I would like to thank you for your excellent work. I read your article and ran the model at 10 epochs, but my metric is a little different from the one presented in the article. I could not find the exact number of epochs in the article. Please can you tell me what is the number of epochs you are using in the training in the article?

**Comment by htcr** [comment]
I'll release our ckpt soon, you may compare your results with it too.

**Comment by htcr** [comment]
Closing, feel free to re-open if further discussion is needed.
