### ISSUE TITLE
can we direct do inference without training? 

### ISSUE THREAD

**Issue by GISScience** [htcr/sam_road#15]
Great work...
I want to do inference on my dataset.

How to do the same. request you to elaborate the steps.

i am unable to set 
RuntimeError: PytorchStreamReader failed reading zip archive.
when i have done 
%cd /content/sam_road/
!pwd
!python /content/sam_road/inferencer.py --checkpoint /content/sam_road/sam_ckpts/sam_vit_b_01ec64.pth --config /content/sam_road/config/toponet_vitb_512_cityscale.yaml --output_dir /content/sam_road/output

**Comment by htcr** [comment]
Can you elaborate the error message? Which line throw that error?
Also I have updated the huggingface link to our trained checkpoints in README. sam_vit_b_01ec64.pth is the SAM ckpt, not yet trained for road network detection.

**Comment by htcr** [comment]
So I'd suggest
1) modify inference.py to suit your own dataset
2) load our pretrained ckpt (you can train your own for best results, it's actually quite fast, within 1-2 hours)

**Comment by htcr** [comment]
Closing, ff to reopen.

**Comment by GISScience** [comment]
solved abvoe but got new error 
Have alook herer - https://colab.research.google.com/drive/1umR11aDGLLwYS_DAv7Yz0BrZJca0fgGr?authuser=1#scrollTo=3duJoD_etNQK

Even after installing detectron2 , i am geeeting this error.. please help..


/content/drive/MyDrive/htcr_sam_road/sam_road
Traceback (most recent call last):
  File "/content/drive/MyDrive/htcr_sam_road/sam_road/inferencer.py", line 247, in <module>
    net = SAMRoad(config)
  File "/content/drive/MyDrive/htcr_sam_road/sam_road/model.py", line 363, in __init__
    new_state_dict = self.resize_sam_pos_embed(ckpt_state_dict, image_size, vit_patch_size, encoder_global_attn_indexes)
  File "/content/drive/MyDrive/htcr_sam_road/sam_road/model.py", line 385, in resize_sam_pos_embed
    pos_embed = new_state_dict['image_encoder.pos_embed']
KeyError: 'image_encoder.pos_embed'

**Comment by HaithemH** [comment]
"/content/drive/MyDrive/htcr_sam_road/sam_road/model.py", line 385, in resize_sam_pos_embed pos_embed = new_state_dict['image_encoder.pos_embed'] KeyError: 'image_encoder.pos_embed'

Same error for both checkpoints.
