### ISSUE TITLE
Comparison experiment code request

### ISSUE THREAD

**Issue by 116011** [htcr/sam_road#17]
The comparative experiment is very wonderful. Can you share the code of the comparative experiment, including segmentation-based (Seg-UNet, Seg-DRM, Seg-Improved, Seg-DLA, Sat2Graph) and graph-based (Road-Tracer, RNGDet, RNGDet++)? I would greatly appreciate it.

**Comment by htcr** [comment]
I cited the baseline numbers from the RNGDet++ paper. Can you reach to the auther of that? In addition, if you are experimenting a new method I don't believe you have to run all these baselines as many of them are quite outdated I would say.

**Comment by htcr** [comment]
closing, ff to reopen.
