### ISSUE TITLE
Method of how to generate the GT graph

### ISSUE THREAD

**Issue by Ikaros0123** [htcr/sam_road#18]
Thanks for your great work! 

Do I have to generate the GT graph if I just want to run inferencer.py using the given trained checkpoint? 

I notice line 259, 263, 283 and 284 in inferencer.py, it seems like those code need GT graph of the rgb picture as input. 

And if so, can you kindly share me the code/method to generate the GT graph? I would greatly appreciate it.

**Comment by wfantastic** [comment]
Hello, I would like to ask you this question. Have you found a way to generate GT graph? My own dataset only has the original road remote sensing image and labels.
I hope you can reply me when you have time. Have a good life！
