### ISSUE TITLE
dataset split problem.

### ISSUE THREAD

**Issue by QK51643729** [htcr/sam_road#20]
In this project I see you use 'train' and 'valid' as 'train', 'test' as 'valid', 'test' as 'test', Does this practice lead to data breaches?

**Comment by htcr** [comment]
I don't think so. The validation metric during training in this work was mainly telling whether the model is converging or not, instead of used as a feedback signal to fine-tune the method/architecture. Using other dataset/split methods shall not change the conclusions. Feel free to verify.
