### ISSUE TITLE
The shape of variable accidentally changed

### ISSUE THREAD

**Issue by mwang063** [htcr/sam_road#29]
Hello, thanks so much for your work! I came across a problem when running the model. In the code file model.py about line 140, the code 'pair_features = self.transformer_encoder(pair_features, src_key_padding_mask=padding_mask)' might cause error sometimes.

The shape of pair_features should not be changed before and after self.transformer_encoder, but at some time, its shape might be changed which confused me. Could you find the reason? Thanks a lot!

**Comment by htcr** [comment]
Hi, thank you for your interest - I think the code shall run fine in general for Cityscale and SpaceNet dataset. Have you found a way to reliably reproduce?

**Comment by mwang063** [comment]
Thanks for your reply, i will check my reproduction way and dataset further. Thanks!
