### ISSUE TITLE
Sample vs Point

### ISSUE THREAD

**Issue by EchoQiHeng** [htcr/sam_road#34]
Thank you for sharing your code. I am confused about the difference between "sample_indices" and "nmsed_indices." I don’t understand why **random sampling** is applied to the nmsed_points instead of using **all the nmsed_points**. What is the motivation behind this? Looking forward to your reply.

**Comment by htcr** [comment]
Hi, could you clarify which part of the code you were looking at?

During inference if I remember correctly we do use all the NMS-ed points.
