### ISSUE TITLE
Interested in testing the released trained checkpoints

### ISSUE THREAD

**Issue by rbavery** [htcr/sam_road#4]
Hello, just wanted to say this is very interesting work and I'm keen to test the trained checkpoints when they are available. can they be made available on Huggingface Models?

**Comment by htcr** [comment]
Hi rbavery:

We'll take care of this soon. Please stay tuned.

**Comment by StijnHendrikx** [comment]
I am also very interested in a trained checkpoint of the model. I could not find it anywhere yet, so I was wondering whether it was already available somewhere. Thanks!

**Comment by htcr** [comment]
Our checkpoints have been uploaded to hugging face, see link in README. Closing, feel free to re-open if you encounter issues.
