### ISSUE TITLE
Value of "pixel_mean" and "pixel_std"

### ISSUE THREAD

**Issue by chenpengxin** [htcr/sam_road#7]
This is a great job!

I noticed the hard-coded value of "pixel_mean" and "pixel_std" at https://github.com/htcr/sam_road/blob/main/model.py#L227 .  I wonder why the cityscale and spacenet share the same values?  Could you please give a suggestion of how to set these two values for my customized dataset?

Thanks!

**Comment by htcr** [comment]
Thanks for your interest. These are the values used by SAM if I remembered correctly. I don't think they matter a lot as long as they are reasonable values for natural images.
